#!/bin/bash

PACKAGE_VERSION=`grep  Version:  debian-package/DEBIAN/control | tr -d "[:alpha:]" | tr -d "[:blank:]" | tr -d "[=:=]"`
PACKAGE_NAME=srtmerge-$PACKAGE_VERSION
rm -rf srtmerge-*

cp srtmerge debian-package/usr/lib -R -f
rm debian-package/usr/lib/srtmerge/__init__.py
cp debian-package $PACKAGE_NAME -R

chmod 0755 $PACKAGE_NAME/DEBIAN -R
chmod 0755 $PACKAGE_NAME/usr -R

chgrp root $PACKAGE_NAME/DEBIAN -R
chgrp root $PACKAGE_NAME/usr -R

dpkg --build $PACKAGE_NAME "$PACKAGE_NAME"_all.deb

lintian "$PACKAGE_NAME"_all.deb
